In [1]:
import numpy as np

In [2]:
integers = np.array([10,20,30,40,50])

In [3]:
integers[0]

10

In [6]:
integers[1]=60
integers

array([10, 60, 30, 40, 50])

In [7]:
integers.dtype

dtype('int32')

In [8]:
smallerType = np.array(integers,dtype=np.int8)
smallerType

array([10, 60, 30, 40, 50], dtype=int8)

## Multidimensional arrays

In [10]:
numbers = np.array([[0,2,3,4,5],[6,7,8,9,10]])

In [11]:
numbers

array([[ 0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
numbers.ndim

2

In [13]:
numbers[1,3]

9

In [15]:
multi_numbers = np.array([[[0,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
multi_numbers

array([[[ 0,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [16]:
multi_numbers[0,1,2]

6

## Creating arrays from List and other python structures

In [18]:
python_list = [0,1,2,3,4,5,6,7]
n_arrs = np.array(python_list)
n_arrs

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
python_list_decimal = [0,1.0223,2.23,3.45,4.6,5,6,7]
n_arrs_float = np.array(python_list_decimal)
n_arrs_float

array([0.    , 1.0223, 2.23  , 3.45  , 4.6   , 5.    , 6.    , 7.    ])

In [20]:
n_arrs_float.dtype

dtype('float64')

In [21]:
list_mixed = ['Anne',123123,'Willy',1231]
list_mixed_np = np.array(list_mixed)
list_mixed_np

array(['Anne', '123123', 'Willy', '1231'], dtype='<U11')

In [22]:
tuple_array = (1,2,3,4)
tuple_array_np = np.array(tuple_array)
tuple_array_np

array([1, 2, 3, 4])

## Instrisic NumPy Array Creation

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
np.arange(100,200,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [27]:
np.linspace(100,200) # default 50 samples

array([100.        , 102.04081633, 104.08163265, 106.12244898,
       108.16326531, 110.20408163, 112.24489796, 114.28571429,
       116.32653061, 118.36734694, 120.40816327, 122.44897959,
       124.48979592, 126.53061224, 128.57142857, 130.6122449 ,
       132.65306122, 134.69387755, 136.73469388, 138.7755102 ,
       140.81632653, 142.85714286, 144.89795918, 146.93877551,
       148.97959184, 151.02040816, 153.06122449, 155.10204082,
       157.14285714, 159.18367347, 161.2244898 , 163.26530612,
       165.30612245, 167.34693878, 169.3877551 , 171.42857143,
       173.46938776, 175.51020408, 177.55102041, 179.59183673,
       181.63265306, 183.67346939, 185.71428571, 187.75510204,
       189.79591837, 191.83673469, 193.87755102, 195.91836735,
       197.95918367, 200.        ])

In [26]:
np.linspace(100,200,5)

array([100., 125., 150., 175., 200.])

In [28]:
np.random.rand(10)

array([0.0842162 , 0.35438541, 0.78069307, 0.82803767, 0.81093213,
       0.38391178, 0.03609245, 0.65903862, 0.60994521, 0.64680153])

In [31]:
np.random.rand(10,3) # multi-dimensional

array([[0.69086816, 0.84743949, 0.86341481],
       [0.94034062, 0.98273766, 0.77732415],
       [0.7258863 , 0.27135535, 0.24642048],
       [0.19948074, 0.08577378, 0.10251656],
       [0.91153425, 0.36774935, 0.771344  ],
       [0.05709599, 0.21566515, 0.86277347],
       [0.27564357, 0.97072312, 0.37970083],
       [0.07100105, 0.06551816, 0.92717701],
       [0.45937494, 0.89479487, 0.93908606],
       [0.73581878, 0.87521297, 0.74726981]])

In [32]:
np.random.randint(low=0,high=100,size=20)

array([23,  8,  5, 10, 56, 30, 46, 81,  5, 77, 66,  0, 55,  0,  2, 96, 95,
        4,  1, 78])

## Generate filled constant value arrays

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
empty_array = np.empty(5)
empty_array.fill(12) # one dimension
empty_array

array([12., 12., 12., 12., 12.])

In [43]:
np.full(5,10) # multi dimension

array([10, 10, 10, 10, 10])

In [47]:
np.full((2,5,3),10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [45]:
np.shape(np.ones(10))

(10,)

In [49]:
np.size(np.full((1,5,6),10))

30

## Adding, removing, and sorting elements

In [54]:
main_array = np.array([1,3,5,6])

In [60]:
np.insert(main_array,1,values=2) 

array([1, 2, 3, 5, 6])

In [61]:
second_array=np.array([7,8,9,10])

In [62]:
np.append(main_array,second_array)

array([ 1,  3,  5,  6,  7,  8,  9, 10])

In [66]:
one_array=np.array([1,2,1,3,4,5,6])
np.delete(one_array,2)

array([1, 2, 3, 4, 5, 6])

In [67]:
inte_array = np.random.randint(20,30,5)
inte_array

array([27, 26, 29, 28, 21])

In [68]:
np.sort(inte_array)

array([21, 26, 27, 28, 29])

In [76]:
first_array = np.random.randint(20,30,5)
second_array = np.random.randint(20,30,5)
d_mess = np.array([first_array,second_array])
d_mess

array([[23, 20, 21, 23, 24],
       [22, 28, 29, 27, 26]])

In [141]:
type(first_array)

numpy.ndarray

In [77]:
np.sort(d_mess)

array([[20, 21, 23, 23, 24],
       [22, 26, 27, 28, 29]])

## Copying vs Views

In [79]:
random_numbers = np.random.randint(120,1230,10)
random_numbers

array([ 968,  944,  281,  235,  957, 1096,  163,  665,  391,  786])

In [81]:
new_random_numbers = random_numbers
new_random_numbers

array([ 968,  944,  281,  235,  957, 1096,  163,  665,  391,  786])

In [84]:
new_random_numbers[0]= 10
print(new_random_numbers)
print(random_numbers)

[  10  944  281  235  957 1096  163  665  391  786]
[  10  944  281  235  957 1096  163  665  391  786]


In [86]:
copy_rand_number = random_numbers.copy()
copy_rand_number[0]= 100
print(random_numbers)
print(copy_rand_number)

[  10  944  281  235  957 1096  163  665  391  786]
[ 100  944  281  235  957 1096  163  665  391  786]


In [88]:
view_random_number=random_numbers.view()
view_random_number[0]=200
print("orig",random_numbers)
print("view",view_random_number)

orig [ 200  944  281  235  957 1096  163  665  391  786]
view [ 200  944  281  235  957 1096  163  665  391  786]


In [90]:

print("orig",random_numbers.base)
print("clone?",new_random_numbers.base)
print("copy",copy_rand_number.base)
print("view",view_random_number.base)

orig None
clone? None
copy None
view [ 200  944  281  235  957 1096  163  665  391  786]


## Reshaping arrays

In [92]:
first_arr = np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [93]:
second_arr = np.reshape(first_arr, (3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
third_array=np.reshape(first_arr,(6,2))
third_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [100]:
fourth_array=np.reshape(first_arr,(3,4,1))
fourth_array

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [101]:
fifth_array=np.reshape(fourth_array,-1)
fifth_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [109]:
sixth_array = fourth_array.flatten()  # copy
print(sixth_array)
print(sixth_array.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
None


In [110]:
seventh_array = fourth_array.ravel() # view
print(seventh_array)
print(seventh_array.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [113]:
sixth_array[0]=10
seventh_array[0]=20
print(fourth_array)
print(sixth_array) # copy
print(seventh_array) # view

[[[20]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
[10  2  3  4  5  6  7  8  9 10 11 12]
[20  2  3  4  5  6  7  8  9 10 11 12]


## Indexing and Slicing

In [117]:
sample_array = np.linspace(10,50,6)
sample_array

array([10., 18., 26., 34., 42., 50.])

In [124]:
sample_array[0:3]

array([10., 18., 26.])

In [126]:
sample_array[4:]

array([42., 50.])

In [127]:
sample_array[2::2]

array([26., 42.])

In [128]:
sample_array[:-2:2]

array([10., 26.])

In [118]:
sample_array[-1]

50.0

In [120]:
sample_arra2 = np.reshape(sample_array,(3,2,1))
sample_arra2

array([[[10.],
        [18.]],

       [[26.],
        [34.]],

       [[42.],
        [50.]]])

In [121]:
sample_arra2[1,-1,-1]

34.0

In [129]:
sample_arra3 = np.reshape(sample_array,(3,2))
sample_arra3

array([[10., 18.],
       [26., 34.],
       [42., 50.]])

In [136]:
sample_arra3[2,1:]

array([50.])

## Joining and splitting arrays

#### Joining 

In [153]:
fir_arr = np.arange(1,11)
sec_arr = np.arange(11,21)
np.concatenate((fir_arr,sec_arr))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [162]:
third_arr = np.concatenate((fir_arr,sec_arr))
third_arr= np.reshape(third_arr,(2,10))
print(third_arr)
print()
fourth_arr = np.array([np.arange(21,31),np.arange(31,41)])
fourth_arr= np.reshape(fourth_arr,(2,10))
print(fourth_arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [163]:
np.concatenate((third_arr,fourth_arr),axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [157]:
np.concatenate((third_arr,fourth_arr),axis=1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40]])

In [159]:
np.stack((third_arr,fourth_arr))

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]])

In [160]:
np.hstack((third_arr,fourth_arr))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40]])

In [161]:
np.vstack((third_arr,fourth_arr))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

#### Splitting 

In [165]:
array = np.arange(1,13)


In [171]:
np.array_split(array,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [167]:
np.array_split(array,8)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [177]:
twoD_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
twoD_array_split = np.hsplit(twoD_array,5)
twoD_array_split

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [182]:
twoD_array_split[0][1]

array([6])

In [184]:
np.vsplit(twoD_array,2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

## Arithmetric Operations

In [2]:
a = np.arange(1,11)
b = np.arange(21,31)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[21 22 23 24 25 26 27 28 29 30]


In [3]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [4]:
a-b

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [5]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [6]:
a/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [7]:
a**b

array([          1,     4194304,  -346101685,           0,   167814181,
       -1543503872,    17998615,           0, -1635065239,  1073741824])

In [10]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [12]:
np.power(a,2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [14]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

## Broadcasting

In [16]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b =np.arange(1,4)
b

array([1, 2, 3])

In [18]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [20]:
c = np.arange(1,3)
c

array([1, 2])

In [23]:
d = np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
e = np.arange(4)
e

array([0, 1, 2, 3])

In [25]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

## Aggregate function

In [27]:
first_arr = np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [28]:
first_arr.sum()

550

In [30]:
sec_arr= np.arange(10,100,10).reshape(3,3)
sec_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [34]:
sec_arr.sum(axis=0) # row

array([120, 150, 180])

In [33]:
sec_arr.sum(axis=1)# col

array([ 60, 150, 240])

In [35]:
sec_arr.prod(axis=0) # row

array([ 28000,  80000, 162000])

In [36]:
sec_arr.prod(axis=1) # col

array([  6000, 120000, 504000])

In [37]:
np.average(first_arr)

55.0

In [38]:
np.min(first_arr)

10

In [39]:
np.max(first_arr)

100

In [43]:
np.max(sec_arr,axis=0)

array([70, 80, 90])

In [44]:
np.max(sec_arr,axis=1)

array([30, 60, 90])

In [45]:
np.mean(first_arr)

55.0

In [46]:
np.std(first_arr)

28.722813232690143

## Distinct and counts

In [50]:
arr= np.array([[1,2,3,2],[2,3,2,4],[1,4,8,8],[1,2,3,2]])
np.unique(arr)

array([1, 2, 3, 4, 8])

In [52]:
np.unique(arr,axis=0)

array([[1, 2, 3, 2],
       [1, 4, 8, 8],
       [2, 3, 2, 4]])

In [53]:
arr= np.array([[1,1,3,2],[2,2,2,4],[1,1,8,8],[1,1,3,2]])
np.unique(arr,axis=1)

array([[1, 2, 3],
       [2, 4, 2],
       [1, 8, 8],
       [1, 2, 3]])

In [54]:
np.unique(arr,return_index=True)

(array([1, 2, 3, 4, 8]), array([ 0,  3,  2,  7, 10], dtype=int64))

In [55]:
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 8]), array([6, 5, 2, 1, 2], dtype=int64))

## Transpose like operations

In [56]:
first_2d = np.arange(12).reshape((3,4))
first_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
np.transpose(first_2d)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [59]:
sec_2d = np.arange(6).reshape(3,2)
sec_2d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
np.transpose(sec_2d,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [61]:
np.transpose(sec_2d)

array([[0, 2, 4],
       [1, 3, 5]])

In [62]:
third_2d = np.arange(24).reshape(2,3,4)
third_2d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [63]:
np.moveaxis(third_2d,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [65]:
np.swapaxes(third_2d,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## Reversing array

In [68]:
arr

array([[1, 1, 3, 2],
       [2, 2, 2, 4],
       [1, 1, 8, 8],
       [1, 1, 3, 2]])

In [69]:
np.flip(arr)

array([[2, 3, 1, 1],
       [8, 8, 1, 1],
       [4, 2, 2, 2],
       [2, 3, 1, 1]])

In [70]:
np.flip(arr,1)

array([[2, 3, 1, 1],
       [4, 2, 2, 2],
       [8, 8, 1, 1],
       [2, 3, 1, 1]])